version: '3.9'

services:
  django:
    image: django_app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DOCKER_HOST=unix:///var/run/docker.sock
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"

  celery:
    image: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A realtime_code_editor worker --loglevel=info
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DOCKER_HOST=unix:///var/run/docker.sock
      - POSTGRES_DB=codematedb
      - POSTGRES_USER=codemate
      - POSTGRES_PASSWORD=codemate1234
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

  environment:
    image: environment
    build:
      context: .
      dockerfile: Dockerfile.environment
    working_dir: /code_file
    tty: true

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: codematedb
      POSTGRES_USER: codemate
      POSTGRES_PASSWORD: codemate1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
