services:
  django:
    image: django_app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    # command: daphne -b 0.0.0.0 -p 8000 realtime_code_editor.asgi:application
    # command: daphne -b 0.0.0.0 -p $PORT realtime_code_editor.asgi:application
    command: python manage.py runserver 0.0.0.0:8000

    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DOCKER_HOST=unix:///var/run/docker.sock

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"

  celery:
    image: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A realtime_code_editor worker --loglevel=info
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DOCKER_HOST=unix:///var/run/docker.sock

  environment:
    image: environment
    build:
      context: .
      dockerfile: Dockerfile.environment
    working_dir: /code_file
    tty: true
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx_server
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./staticfiles:/app/staticfiles
  #   depends_on:
  #     - django
